src/account/urls.py
from django.contrib.auth import views as auth_views #built-in auth.
from django.urls import path
from .import views

app_name = 'account'

urlpatterns = [
    path('register/',
        views.signup,
        name='sign-up'),

    path('login/',
        auth_views.LoginView.as_view(template_name='account/login.html'), 
        name='sign-in'),

    path('logout/',
        auth_views.LogoutView.as_view(),
        name='sign-out'),

    path('update/user/',
        views.UserUpdateView.as_view(),
        name='update_account'),

    path('server-side/validate/username/',
        views.validate_username,
        name='validate_username'),

    path('reset/',auth_views.PasswordResetView.as_view(
    	template_name='account/password_reset.html',
    	email_template_name='account/password_reset_email.html',
    	subject_template_name='account/password_reset_subject.txt'),
    name = 'password_reset'),

    path('reset/done/',auth_views.PasswordResetDoneView.as_view(
    	template_name='account/password_reset_done.html'),
    name = 'password_reset_done'),

    path('reset/<str:uidb64>/<str:token>/',auth_views.PasswordResetConfirmView.as_view(
    	template_name='account/password_reset_confirm.html'),
    name = 'password_reset_confirm'),

    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(
    	template_name='account/password_reset_complete.html'),
    name = 'password_reset_complete'),

]

src/boards/urls.py
from django.urls import path
from . import views as v
from files import views as v2
from financial_system import views as v3
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boards'

urlpatterns = [
    path("boards/newboard/", 
        v.new_board, 
        name="new_board"),

    path("files/upload/", 
        v2.home, 
        name="file"),

    path('files/uploadfile/',
        v2.uploadfile,
        name="uploadfile"),

    path('files/deleteFile/<int:id>',
        v2.deleteFile,
        name="deletefile"),

    path('financial_system/stocks/',
        v3.StocksListView.as_view(),
        name='stocks'),

    path('financial_system/stocks/stock_transaction/<int:id>',
        v3.stock_transaction,
        name="stock_transaction"),

    path('financial_system/properties/',
        v3.PropertiesListView.as_view(),
        name='properties'),

    path("financial_system/properties/new_property/", 
        v3.new_property, 
        name="new_property"),

    path('financial_system/bonds/',
        v3.BondsListView.as_view(),
        name='bonds'),

    path("financial_system/bonds/new_bond/", 
        v3.new_bond, 
        name="new_bond"),

    path('financial_system/properties/property_transaction/<int:id>',
        v3.property_transaction,
        name="property_transaction"),

    path('financial_system/misc_products/',
        v3.MiscListView.as_view(),
        name='misc_products'),

    path("financial_system/misc_products/new_misc_product/", 
        v3.new_misc_product, 
        name="new_misc_product"),

    path('financial_system/misc_products/other_transaction/<int:id>',
        v3.other_transaction,
        name="other_transaction"),

    path("financial_system/user_transactions_form/", 
        v3.user_transactions_form, 
        name="user_transactions_form"),

    path("financial_system/user_transactions_form/list_user_transactions/", 
        v3.list_user_transactions, 
        name="list_user_transactions"),

    path("financial_system/stock_date_form/", 
        v3.stock_date_form, 
        name="stock_date_form"),

    path("financial_system/stock_date_form/list_stocks_on_date/", 
        v3.list_stocks_on_date, 
        name="list_stocks_on_date"),

    path("financial_system/property_data_form/", 
        v3.property_data_form, 
        name="property_data_form"),

    path("financial_system/property_data_form/list_property_data/", 
        v3.list_property_data, 
        name="list_property_data"),

    path("financial_system/bond_data_form/", 
        v3.bond_data_form, 
        name="bond_data_form"),

    path("financial_system/bond_data_form/list_bond_data/", 
        v3.list_bond_data, 
        name="list_bond_data"),

    path("financial_system/agent_assets_form/", 
        v3.agent_assets_form, 
        name="agent_assets_form"),

    path("financial_system/agent_assets_form/list_agent_assets/", 
        v3.list_agent_assets, 
        name="list_agent_assets"),

    path("financial_system/loan_ratings_form/", 
        v3.loan_ratings_form, 
        name="loan_ratings_form"),

    path("financial_system/loan_ratings_form/list_loan_ratings/", 
        v3.list_loan_ratings, 
        name="list_loan_ratings"),
        
    path("financial_system/add_user_expenditures/", 
        v3.add_user_expenditures, 
        name="add_user_expenditures"),

    path("financial_system/expenditure_date_form/", 
        v3.expenditure_date_form, 
        name="expenditure_date_form"),

    path("financial_system/expenditure_date_form/list_expenditures/", 
        v3.list_expenditures, 
        name="list_expenditures"),

    path('',
        v.BoardListView.as_view(),
        name='board_index'),

    path('boards/<str:pk>/',
        v.BoardTopicsListView.as_view(),
        name='board_topics'),

    path('boards/<str:pk>/new/topic',
    	v.new_topic,
    	name='new_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/',
        v.TopicPostListView.as_view(),
        name='topic_posts'),


    path('boards/<str:board_pk>/topics/<str:topic_pk>/reply/',
    	v.reply_topic,
    	name='reply_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/posts/<str:post_pk>/edit/',
    	v.PostUpdateView.as_view(),
    	name='update_post'),
]

src/files/urls.py
from django.urls import path
from files import views

app_name = 'files'

urlpatterns = [

]

src/boards/models.py
import math
import uuid
from django.utils.html import mark_safe
from markdown import markdown
from django.conf import settings
from django.utils.text import Truncator
from django.db import models

class Board(models.Model):
	"""
	Board Model
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	name = models.CharField(max_length=125,unique=True)
	description = models.TextField(max_length = 255)

	created	= models.DateTimeField(auto_now_add = True)
	updated	= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Board'
		verbose_name_plural = 'Boards'

	def __str__(self):

		return self.name if self.name else None

	@property	
	def get_posts_count(self):

		return Post.objects.filter(topic__board = self).count()

	@property
	def get_last_post(self):

		return Post.objects.filter(topic__board = self).first()

class Topic(models.Model):
	"""
	Topic Model
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	subject = models.CharField(max_length=125)
	board = models.ForeignKey(Board,related_name='topics',on_delete=models.SET_NULL,null=True)
	starter = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='user_topics')
	views = models.PositiveSmallIntegerField(default = 0) #viewers counter
	created	= models.DateTimeField(auto_now_add = True)
	updated	= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Topic'
		verbose_name_plural = 'Topics'

	def __str__(self):
		return "{0} by {1}".format(self.subject,
			self.starter.username) if self.starter and self.subject else None

	def get_page_count(self):
		count = self.posts.count()
		pages = count/2
		return math.ceil(pages)

	def get_last_3_posts(self):

		return self.posts.all()[:3]

	def has_many_pages(self,count=None):
		if count is None:
			count = self.get_page_count()
		return count > 2

	def get_page_range(self):
		count = self.get_page_count()
		if self.has_many_pages(count):
			return range(1,3)
		return range(1,count + 1)

class Post(models.Model):
	"""
	Post Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	message		= models.TextField(max_length=125)
	topic 		= models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
	created_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user_posts',on_delete=models.CASCADE)
	updated_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='+',null=True,on_delete=models.SET_NULL)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'

	def __str__(self):
		message_truc_obj = Truncator(self.message)
		return message_truc_obj.chars(13)

	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message,safe_mode='escape'))

src/boards/forms.py
from django import forms
from .import models

class NewTopicForm(forms.ModelForm):
	message = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':"Type something..."}),
		max_length=250,
		help_text="250 words max.")

	class Meta:
		model  = models.Topic
		fields = ['subject','message']
	 
class PostForm(forms.ModelForm):

	class Meta:
		model = models.Post
		fields = ['message',]

class NewBoardForm(forms.ModelForm):
	name = forms.CharField(max_length=125)
	description = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':"Type something..."}),
		max_length=250,
		help_text="250 words max.")

	class Meta:
		model = models.Board
		fields = ['name', 'description']

src/boards/views.py
from django.utils import timezone
from django.db.models import Count
from django.urls import resolve,reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView,ListView
import pandas as pd
import numpy as np
import time
import datetime
from decimal import Decimal
from financial_system.models import StockData, Stock

from .forms import NewTopicForm,PostForm, NewBoardForm
from .models import Board,Topic,Post

def scrape_stocks():

	tickers = {
		"AAPL": 2,
		"MSFT": 3,
		"CSCO": 4,
		"META": 5,
		"AMZN": 6,
		"TSLA": 7,
		"NFLX": 8,
		"GOOGL": 9,
		"HOOD": 10
	}

	for key, value in tickers.items():
		ticker = key
		id = value
		period1 = int(time.mktime(datetime.datetime(2022, 11, 25, 23, 59).timetuple()))
		period2 = int(time.mktime(datetime.datetime.now().timetuple()))
		interval = '1d'

		query_string = f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'

		data = pd.read_csv(query_string)
		
		date = data['Date'].tolist()[0]
		open = data['Open'].tolist()[0]
		high = data['High'].tolist()[0]
		low = data['Low'].tolist()[0]
		close = data['Close'].tolist()[0]
		volume = data['Volume'].tolist()[0]

		stock_object = Stock.objects.get(id=id)

		stock_check = StockData.objects.filter(date=date, stock_id=id).exists()

		if stock_check == False:
			s = StockData(open_price=open, close_price=close, high_price=high, low_price=low, volume=volume, date=date, stock=stock_object)
			s.save()

scrape_stocks()

class BoardListView(ListView):

	model = Board
	context_object_name = 'boards'
	template_name = 'boards/index.html'

class BoardTopicsListView(ListView):

	model = Topic
	context_object_name = 'topics'
	template_name = 'boards/topics.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):
		"""
		overrides context
		"""
		kwargs['board'] = self.board
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		"""
		overrides queryset
		"""
		self.board = get_object_or_404(Board,pk=self.kwargs.get('pk'))
		queryset = self.board.topics.annotate(replies = Count('posts') - 1)
		return queryset

@login_required
def new_topic(request,pk):

	current_user = request.user

	context = dict()
	board = get_object_or_404(Board,id = pk)
	form =  NewTopicForm()
	if request.method == 'POST':
		form =  NewTopicForm(data = request.POST)
		if form.is_valid():
			topic_instance = form.save(commit=False)
			topic_instance.board = board
			topic_instance.starter = current_user
			topic_instance.save()

			post,_ = Post.objects.get_or_create(message = request.POST.get('message'),
				topic = topic_instance,
				created_by = current_user)
			return redirect('boards:board_topics',pk = board.pk)
		else:
			pass
			
	template = 'boards/new_topic.html'	
	context['board'] = board
	context['form'] = form
	return render(request,template,context)

@login_required
def new_board(request):
	context = dict()
	form = NewBoardForm()
	if request.method == 'POST':
		form = NewBoardForm(request.POST)

		if form.is_valid():
			name = form.cleaned_data["name"]
			description = form.cleaned_data["description"]

			b = Board(name=name, description=description)
			b.save()

			return redirect('/')

		else:
			pass

	template = 'boards/newboard.html'
	context['form'] = form

	return render(request,template,context)

class TopicPostListView(ListView):

	model = Post
	context_object_name = 'posts'
	template_name = 'boards/topic_posts.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):

		session_key = 'viewed_topic_{}'.format(self.topic.pk)

		if not self.request.session.get(session_key,False):
			self.topic.views += 1
			self.topic.save() 
			self.request.session[session_key] = True

		kwargs['topic'] = self.topic
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		self.topic = get_object_or_404(Topic,
			board__pk=self.kwargs.get('board_pk'),
			pk=self.kwargs.get('topic_pk'))

		queryset = self.topic.posts.order_by('-created')
		return queryset

@login_required
def reply_topic(request,board_pk,topic_pk):
    topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
    if request.method == 'POST':
        form = PostForm(data = request.POST)
        if form.is_valid():
            post_instance = form.save(commit=False)
            post_instance.topic = topic
            post_instance.created_by = request.user
            post_instance.save()

            topic.update = timezone.now()
            topic.save()
            # Bug - Fix it !
            return redirect('boards:topic_posts', 
            	board_pk = str(board_pk),
            	topic_pk = str(topic_pk))

        else:
        	pass
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html',{'topic': topic, 'form': form})

@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):

	model = Post
	fields = ('message',)
	template_name = 'boards/edit_post.html'
	pk_url_kwarg = 'post_pk'
	context_object_name = 'post'

	def get_queryset(self):
		queryset = super().get_queryset()
		current_user = self.request.user
		user_only_post = queryset.filter(created_by = current_user)
		return user_only_post

	def form_valid(self,form):
		"""
		handling form validation - dev.
		"""
		post = form.save(commit = False)
		post.updated_by = self.request.user
		post.save()
		return redirect('boards:topic_posts', 
            	board_pk = post.topic.board.pk,
            	topic_pk = post.topic.pk)

src/boards/templates/boards/partials/_form.html
<!-- 
Re-useability of form rendered template
 -->

 {% load widget_tweaks %}
 <!-- form body -->
   <!-- render error--->
     {% if form.non_field_errors %}
       <div class="alert alert-danger" role="alert">
         {% for error in form.non_field_errors %}
           <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
         {% endfor %}
       </div>
     {% endif %}
   <!-- /render error--->
  {% for field in form %}
     <div class="form-group">
       {{ field.label_tag }}

       <!-- error fields style -->
       {% if form.is_bound %}<!-- a bound form fields -->
             {% if field.errors %}

               {% render_field field class="form-control is-invalid" %}
               {% for error in field.errors %}
                 <div class="invalid-feedback">
                   {{ error }}
                 </div>
               {% endfor %}

             {% else %}
               {% render_field field class="form-control is-valid" %}
             {% endif %}
       <!-- /error fields styles --> 
       {% else %} <!-- / bound form fields -->
             {% render_field field class="form-control" %} <!-- unbound form fields -->
       {% endif %}

       {% if field.help_text %}
         <small class="form-text text-muted">
           {{ field.help_text }} <!-- render help text -->
         </small>
       {% endif %}
     </div>
{% endfor %}
 <!-- /form body -->

src/boards/templates/boards/partials/_nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
      * {
        margin:0;
        padding:0;
      }
      body {
        background-color:#0088ff;
        font-family: 'Raleway', sans-serif;
      }
      #ribbon {
        position:absolute;
        background-color:red;
        color:white;
        top:40px;
        left:-30px;
        width:160px;
        transform:rotate(-45deg);
        text-align:center;
      }
      #container {
        position:relative;
        margin-left:auto;
        margin-right:auto;
        width:90%;
        background-color:black;
        box-shadow: -2px -2px 5px white,2px -2px 5px white;
      }
      #container > nav {
        width:100%;
        display:flex;
        max-height:60px;
      }
      #logo {
        line-height:60px;
        font-size:30px;
        padding: 0 50px;
        color: white;
        width:40%;
        letter-spacing:2px;
        text-shadow:2px 2px 5px;
      }
      #container > nav > ul {
        margin:0;
        padding:0;
        list-style-type:none;
        display:flex;
        position:absolute;
          right:50px;
      /*   min-width:60%; */
      }
      #container > nav > ul > li {
        line-height:60px;
        margin: 0 0px;
        padding:0;
        text-align:center;
        display:inline-block;
        
      /*   background-color:green; */
        min-width:120px;
      
      } 
      #container > nav > ul > li > a {
        position:relative;
      /*   background-color:red; */
        margin: 0 20px;
          color:white;
      }
      #container > nav > ul > li:hover {
        border-bottom: 2px solid white;
        background-color: #0088ff;
      }
      #container > nav > ul > .dropdown:hover {
        border-bottom:none;
      }
      #container > nav > ul > .dropdown:hover >  .dd
      {
        display:block;
      }
      .dropdown:hover > a .fa-caret-down {
        display:none;
      }
      a {
        text-decoration:none;
      
      }
      
      #container > nav > ul > li > div {
        position:absolute;
        padding: 0 10px;
        
        background-color:black;
        display:none;
        background-color:aliceblue;
        min-width:100px;
      }
      
      #container > nav > ul > li > div > ul {
        margin:0px 0 10px 0;
        padding:0;
        list-style:none;
      }
      #u_a_c {
        position:relative;
        width:100%;
      /*   background-color:red; */
      }
      #up_arrow {
        position:relative;
        width:20px;
        height:20px;
        left:42%;
        top:-10px;
        background-color:aliceblue;
        transform:rotate(45deg);
      }
      #container > nav > ul > li> div > ul > li:hover {
        background-color:rgba(0,0,0,0.2);
      }
      #container > nav > ul > li > div > ul > li > a {
        padding : 5px;
          color:black;
      }
    </style>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <!-- Navigation -->
  <div id="container">
    <div class="navbar navbar-default">
      <a href="{% url 'boards:board_index' %}">Home</a>
      <li class="dropdown" style="list-style: none; padding-left: 18px;">
        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">Resources</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/files/upload/">File Manager</a>
          <a class="dropdown-item" href="https://calendar.google.com/calendar">Google Calendar</a>
        </div>
      </li>
      <li class="dropdown" style="list-style: none; padding-left: 18px;">
        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">Financial System</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/financial_system/stocks/">Stocks</a>
          <a class="dropdown-item" href="/financial_system/bonds/">Bonds</a>
          <a class="dropdown-item" href="/financial_system/properties/">Properties</a>
          <a class="dropdown-item" href="/financial_system/misc_products/">Other Products</a>
          <a class="dropdown-item" href="/financial_system/add_user_expenditures/">Add User Expenditures</a>
        </div>
      </li>
      <li class="dropdown" style="list-style: none; padding-left: 18px;">
        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">Financial Query System</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/financial_system/user_transactions_form/">View User Transactions By Date</a>
          <a class="dropdown-item" href="/financial_system/stock_date_form/">View Stock Data By Date</a>
          <a class="dropdown-item" href="/financial_system/property_data_form/">View Data for Property</a>
          <a class="dropdown-item" href="/financial_system/agent_assets_form/">View Assets for Agent</a>
          <a class="dropdown-item" href="/financial_system/bond_data_form/">View Data for Bond</a>
          <a class="dropdown-item" href="/financial_system/loan_ratings_form/">View Loan Ratings for Bank</a>
          <a class="dropdown-item" href="/financial_system/expenditure_date_form/">View User Expenditures</a>
        </div>
      </li>
      {% if request.user.is_authenticated %}
      <form class="form-inline ml-auto">
        <a style="padding:10px" href="{% url 'account:update_account' %}">My Account</a>
        <a href="{% url 'account:sign-out' %}">Log out</a>
      </form>
      {% else %}
        <form class="form-inline ml-auto">
          <a style="padding:10px;" href="{% url 'account:sign-in' %}">Log in</a>
          <a href="{% url 'account:sign-up' %}">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</body>
</html>

src/boards/templates/boards/partials/_pagination.html
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination justify-content-end  pagination-md">
      {% if page_obj.number > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">First</span>
        </li>
      {% endif %}

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}

      {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}