src/boards/urls.py
from django.urls import path
from . import views as v
from files import views as v2
from financial_system import views as v3
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boards'

urlpatterns = [
    path("boards/newboard/", 
        v.new_board, 
        name="new_board"),

    path("files/upload/", 
        v2.home, 
        name="file"),

    path('files/uploadfile/',
        v2.uploadfile,
        name="uploadfile"),

    path('files/deleteFile/<int:id>',
        v2.deleteFile,
        name="deletefile"),

    path('financial_system/stocks/',
        v3.StocksListView.as_view(),
        name='stocks'),

    path('financial_system/stocks/stock_transaction/<int:id>',
        v3.stock_transaction,
        name="stock_transaction"),

    path('financial_system/properties/',
        v3.PropertiesListView.as_view(),
        name='properties'),

    path("financial_system/properties/new_property/", 
        v3.new_property, 
        name="new_property"),

    path('financial_system/bonds/',
        v3.BondsListView.as_view(),
        name='bonds'),

    path("financial_system/bonds/new_bond/", 
        v3.new_bond, 
        name="new_bond"),

    path('financial_system/properties/property_transaction/<int:id>',
        v3.property_transaction,
        name="property_transaction"),

    path('financial_system/misc_products/',
        v3.MiscListView.as_view(),
        name='misc_products'),

    path("financial_system/misc_products/new_misc_product/", 
        v3.new_misc_product, 
        name="new_misc_product"),

    path('financial_system/misc_products/other_transaction/<int:id>',
        v3.other_transaction,
        name="other_transaction"),

    path("financial_system/user_transactions_form/", 
        v3.user_transactions_form, 
        name="user_transactions_form"),

    path("financial_system/user_transactions_form/list_user_transactions/", 
        v3.list_user_transactions, 
        name="list_user_transactions"),

    path("financial_system/stock_date_form/", 
        v3.stock_date_form, 
        name="stock_date_form"),

    path("financial_system/stock_date_form/list_stocks_on_date/", 
        v3.list_stocks_on_date, 
        name="list_stocks_on_date"),

    path("financial_system/property_data_form/", 
        v3.property_data_form, 
        name="property_data_form"),

    path("financial_system/property_data_form/list_property_data/", 
        v3.list_property_data, 
        name="list_property_data"),

    path("financial_system/bond_data_form/", 
        v3.bond_data_form, 
        name="bond_data_form"),

    path("financial_system/bond_data_form/list_bond_data/", 
        v3.list_bond_data, 
        name="list_bond_data"),

    path("financial_system/agent_assets_form/", 
        v3.agent_assets_form, 
        name="agent_assets_form"),

    path("financial_system/agent_assets_form/list_agent_assets/", 
        v3.list_agent_assets, 
        name="list_agent_assets"),

    path("financial_system/loan_ratings_form/", 
        v3.loan_ratings_form, 
        name="loan_ratings_form"),

    path("financial_system/loan_ratings_form/list_loan_ratings/", 
        v3.list_loan_ratings, 
        name="list_loan_ratings"),
        
    path("financial_system/add_user_expenditures/", 
        v3.add_user_expenditures, 
        name="add_user_expenditures"),

    path("financial_system/expenditure_date_form/", 
        v3.expenditure_date_form, 
        name="expenditure_date_form"),

    path("financial_system/expenditure_date_form/list_expenditures/", 
        v3.list_expenditures, 
        name="list_expenditures"),

    path('',
        v.BoardListView.as_view(),
        name='board_index'),

    path('boards/<str:pk>/',
        v.BoardTopicsListView.as_view(),
        name='board_topics'),

    path('boards/<str:pk>/new/topic',
    	v.new_topic,
    	name='new_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/',
        v.TopicPostListView.as_view(),
        name='topic_posts'),


    path('boards/<str:board_pk>/topics/<str:topic_pk>/reply/',
    	v.reply_topic,
    	name='reply_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/posts/<str:post_pk>/edit/',
    	v.PostUpdateView.as_view(),
    	name='update_post'),
]

src/files/urls.py
from django.urls import path
from files import views

app_name = 'files'

urlpatterns = [

]

src/boards/models.py
import math
import uuid
from django.utils.html import mark_safe
from markdown import markdown
from django.conf import settings
from django.utils.text import Truncator
from django.db import models

class Board(models.Model):
	"""
	Board Model
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	name = models.CharField(max_length=125,unique=True)
	description = models.TextField(max_length = 255)

	created	= models.DateTimeField(auto_now_add = True)
	updated	= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Board'
		verbose_name_plural = 'Boards'

	def __str__(self):

		return self.name if self.name else None

	@property	
	def get_posts_count(self):

		return Post.objects.filter(topic__board = self).count()

	@property
	def get_last_post(self):

		return Post.objects.filter(topic__board = self).first()

class Topic(models.Model):
	"""
	Topic Model
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	subject = models.CharField(max_length=125)
	board = models.ForeignKey(Board,related_name='topics',on_delete=models.SET_NULL,null=True)
	starter = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='user_topics')
	views = models.PositiveSmallIntegerField(default = 0) #viewers counter
	created	= models.DateTimeField(auto_now_add = True)
	updated	= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Topic'
		verbose_name_plural = 'Topics'

	def __str__(self):
		return "{0} by {1}".format(self.subject,
			self.starter.username) if self.starter and self.subject else None

	def get_page_count(self):
		count = self.posts.count()
		pages = count/2
		return math.ceil(pages)

	def get_last_3_posts(self):

		return self.posts.all()[:3]

	def has_many_pages(self,count=None):
		if count is None:
			count = self.get_page_count()
		return count > 2

	def get_page_range(self):
		count = self.get_page_count()
		if self.has_many_pages(count):
			return range(1,3)
		return range(1,count + 1)

class Post(models.Model):
	"""
	Post Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	message		= models.TextField(max_length=125)
	topic 		= models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
	created_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user_posts',on_delete=models.CASCADE)
	updated_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='+',null=True,on_delete=models.SET_NULL)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'

	def __str__(self):
		message_truc_obj = Truncator(self.message)
		return message_truc_obj.chars(13)

	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message,safe_mode='escape'))

src/boards/forms.py
from django import forms
from .import models

class NewTopicForm(forms.ModelForm):
	message = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':"Type something..."}),
		max_length=250,
		help_text="250 words max.")

	class Meta:
		model  = models.Topic
		fields = ['subject','message']
	 
class PostForm(forms.ModelForm):

	class Meta:
		model = models.Post
		fields = ['message',]

class NewBoardForm(forms.ModelForm):
	name = forms.CharField(max_length=125)
	description = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':"Type something..."}),
		max_length=250,
		help_text="250 words max.")

	class Meta:
		model = models.Board
		fields = ['name', 'description']

src/boards/views.py
from django.utils import timezone
from django.db.models import Count
from django.urls import resolve,reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView,ListView
import pandas as pd
import numpy as np
import time
import datetime
from decimal import Decimal
from financial_system.models import StockData, Stock

from .forms import NewTopicForm,PostForm, NewBoardForm
from .models import Board,Topic,Post

def scrape_stocks():

	tickers = {
		"AAPL": 2,
		"MSFT": 3,
		"CSCO": 4,
		"META": 5,
		"AMZN": 6,
		"TSLA": 7,
		"NFLX": 8,
		"GOOGL": 9,
		"HOOD": 10
	}

	for key, value in tickers.items():
		ticker = key
		id = value
		period1 = int(time.mktime(datetime.datetime(2022, 11, 25, 23, 59).timetuple()))
		period2 = int(time.mktime(datetime.datetime.now().timetuple()))
		interval = '1d'

		query_string = f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'

		data = pd.read_csv(query_string)
		
		date = data['Date'].tolist()[0]
		open = data['Open'].tolist()[0]
		high = data['High'].tolist()[0]
		low = data['Low'].tolist()[0]
		close = data['Close'].tolist()[0]
		volume = data['Volume'].tolist()[0]

		stock_object = Stock.objects.get(id=id)

		stock_check = StockData.objects.filter(date=date, stock_id=id).exists()

		if stock_check == False:
			s = StockData(open_price=open, close_price=close, high_price=high, low_price=low, volume=volume, date=date, stock=stock_object)
			s.save()

scrape_stocks()

class BoardListView(ListView):

	model = Board
	context_object_name = 'boards'
	template_name = 'boards/index.html'

class BoardTopicsListView(ListView):

	model = Topic
	context_object_name = 'topics'
	template_name = 'boards/topics.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):
		"""
		overrides context
		"""
		kwargs['board'] = self.board
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		"""
		overrides queryset
		"""
		self.board = get_object_or_404(Board,pk=self.kwargs.get('pk'))
		queryset = self.board.topics.annotate(replies = Count('posts') - 1)
		return queryset

@login_required
def new_topic(request,pk):

	current_user = request.user

	context = dict()
	board = get_object_or_404(Board,id = pk)
	form =  NewTopicForm()
	if request.method == 'POST':
		form =  NewTopicForm(data = request.POST)
		if form.is_valid():
			topic_instance = form.save(commit=False)
			topic_instance.board = board
			topic_instance.starter = current_user
			topic_instance.save()

			post,_ = Post.objects.get_or_create(message = request.POST.get('message'),
				topic = topic_instance,
				created_by = current_user)
			return redirect('boards:board_topics',pk = board.pk)
		else:
			pass
			
	template = 'boards/new_topic.html'	
	context['board'] = board
	context['form'] = form
	return render(request,template,context)

@login_required
def new_board(request):
	context = dict()
	form = NewBoardForm()
	if request.method == 'POST':
		form = NewBoardForm(request.POST)

		if form.is_valid():
			name = form.cleaned_data["name"]
			description = form.cleaned_data["description"]

			b = Board(name=name, description=description)
			b.save()

			return redirect('/')

		else:
			pass

	template = 'boards/newboard.html'
	context['form'] = form

	return render(request,template,context)

class TopicPostListView(ListView):

	model = Post
	context_object_name = 'posts'
	template_name = 'boards/topic_posts.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):

		session_key = 'viewed_topic_{}'.format(self.topic.pk)

		if not self.request.session.get(session_key,False):
			self.topic.views += 1
			self.topic.save() 
			self.request.session[session_key] = True

		kwargs['topic'] = self.topic
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		self.topic = get_object_or_404(Topic,
			board__pk=self.kwargs.get('board_pk'),
			pk=self.kwargs.get('topic_pk'))

		queryset = self.topic.posts.order_by('-created')
		return queryset

@login_required
def reply_topic(request,board_pk,topic_pk):
    topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
    if request.method == 'POST':
        form = PostForm(data = request.POST)
        if form.is_valid():
            post_instance = form.save(commit=False)
            post_instance.topic = topic
            post_instance.created_by = request.user
            post_instance.save()

            topic.update = timezone.now()
            topic.save()
            # Bug - Fix it !
            return redirect('boards:topic_posts', 
            	board_pk = str(board_pk),
            	topic_pk = str(topic_pk))

        else:
        	pass
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html',{'topic': topic, 'form': form})

@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):

	model = Post
	fields = ('message',)
	template_name = 'boards/edit_post.html'
	pk_url_kwarg = 'post_pk'
	context_object_name = 'post'

	def get_queryset(self):
		queryset = super().get_queryset()
		current_user = self.request.user
		user_only_post = queryset.filter(created_by = current_user)
		return user_only_post

	def form_valid(self,form):
		"""
		handling form validation - dev.
		"""
		post = form.save(commit = False)
		post.updated_by = self.request.user
		post.save()
		return redirect('boards:topic_posts', 
            	board_pk = post.topic.board.pk,
            	topic_pk = post.topic.pk)

src/boards/templates/boards/edit_post.html
{% extends 'boards/layout/base.html' %}

{% block title %} Post Edit - Discussion Board{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block wrapper %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'boards/partials/_form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

src/boards/templates/boards/index.html
{% extends 'boards/layout/base.html' %}

{% block title %}Board{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block wrapper %}
      <div class="mb-3">
        <a href="/boards/newboard/" class="btn btn-primary">New Discussion Board</a>
      </div>
      
       <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Board Name</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">{{ board.get_posts_count }}</td>
              <td class="align-middle">{{ board.topics.count }}</td>
              <td class="align-middle">
                  {% if board.get_last_post %}
                  <small>
                    <a href="#">
                      {{ board.get_last_post.created_by.username }} at {{ board.get_last_post.created }}
                    </a>
                  </small>
                  {% else %}
                  <small class="text-muted">
                    <em>No posts yet.</em>
                  </small>
                  {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

src/boards/templates/boards/new_topic.html
{% extends 'boards/layout/base.html' %}

{% block title %} New Topic - Discussion Board{% endblock %}


{% block breadcrumb %}
		<li class="breadcrumb-item">
			<a href="{% url 'boards:board_index' %}">Boards</a>
		</li>
		<li class="breadcrumb-item active">
			<a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
		</li>
		<li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block wrapper %}

  <form method="post" action="{% url 'boards:new_topic' board.pk %}" novalidate="novalidate">
    {% csrf_token %}
      {% include 'boards/partials/_form.html' %}
    <div style="text-align:center">
		<button type="submit" style="width:25%;" class="btn btn-success">Post</button>
	</div>
  </form>

{% endblock %}

src/boards/templates/boards/newboard.html
{% extends 'boards/layout/base.html' %}

{% block title %}
New Discussion Board
{% endblock %}

{% block breadcrumb %}
		<li class="breadcrumb-item">
			<a href="{% url 'boards:board_index' %}">Boards</a>
		</li>
		<li class="breadcrumb-item active">New Board</li>
{% endblock %}

{% block wrapper %}

  <form method="post" action="/boards/newboard/" novalidate="novalidate">
    {% csrf_token %}
      {% include 'boards/partials/_form.html' %}
      <div style="text-align:center">
        <button type="submit" style="width:25%;" class="btn btn-success">Create</button>
      </div>
  </form>

{% endblock %}

src/boards/templates/boards/reply_topic.html
{% extends 'boards/layout/base.html' %}

{% load static %}

{% block title %}Post reply - {{ request.user.username }} {% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.id %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.id topic.id %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block wrapper %}

  <form method="post" class="mb-4">
    {% csrf_token %}
     {% include 'boards/partials/_form.html' %}
    <button type="submit" class="btn btn-success">Post reply</button>
  </form>

  {% for post in topic.get_last_3_posts %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created }}</small>
          </div>
        </div>
        {{ post.get_message_as_markdown }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

src/boards/templates/boards/topic_posts.html
{% extends 'boards/layout/base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block wrapper %}


<div class="mb-4">
  <a href="{% url 'boards:reply_topic' topic.board.id topic.id  %}" class="btn btn-primary" role="button">Reply</a>
</div>

  {% for post in posts %}
    <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
          <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'boards/images/user.png' %}" alt="{{ post.created_by.username }}" class="w-100">
            {% if post.created_by.user_posts.count %}
            <small>Posts: {{ post.created_by.user_posts.count }}</small>
            {% endif %}
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created }}</small>
              </div>
            </div>

            {{ post.get_message_as_markdown }}

            {% if post.created_by == request.user %}
              <div class="mt-3">
                <a href="{% url 'boards:update_post' post.topic.board.id post.topic.id post.id %}" 
                class="btn btn-primary btn-sm" role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  
  {% include 'boards/partials/_pagination.html' %}

{% endblock %}

src/boards/templates/boards/topics.html
{% extends 'boards/layout/base.html' %}

{% load humanize %}

{% block title %}Board{% endblock %}

{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
		<li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block wrapper %}

  <div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Topic</th>
        <th>Created By</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Updated</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'boards:topic_posts' topic.board.id topic.id %}">{{ topic.subject }}</a></td>
          <td>{{ topic.starter.username }}</td>
          <td>{{ topic.replies }}</td>
          <td>{{ topic.views }}</td>
          <td>{{ topic.updated|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include 'boards/partials/_pagination.html' %}

{% endblock %}